#!/usr/bin/env npx tsx
/**
 * Build Oxford Phonics World L1–L5 packs + Go! Phonics placeholders.
 * OPW source: ICSpeak community wordlists (unit-aligned).
 * Go! Phonics: no public complete list — fill wordlists/go-phonics-l*.txt from the book.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { kidGloss } from "../src/lib/kid-gloss.ts";
import { makeExample } from "../src/lib/make-example.ts";
import type { DictCore, PackWord, WordPack } from "../src/lib/types.ts";
import { lemmaOf } from "../src/lib/types.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Oxford Phonics World — unit → words (from ICSpeak) */
const OPW: Record<string, { title: string; grade: string; units: [string, string[]][] }> = {
  "opw-l1": {
    title: "Oxford Phonics World 1",
    grade: "Level 1",
    units: [
      ["Unit 1", ["alligator", "ant", "apple", "ax", "banana", "bear", "bed", "bird", "car", "cat", "computer", "cup"]],
      ["Unit 2", ["desk", "dog", "doll", "duck", "egg", "elbow", "elephant", "envelope", "fan", "farm", "fish", "fork"]],
      ["Unit 3", ["gift", "girl", "goat", "gorilla", "hat", "horse", "hot dog", "house", "igloo", "iguana", "ink", "insect"]],
      ["Unit 4", ["jacket", "jam", "jet", "juice", "kangaroo", "key", "king", "kite", "lamp", "leaf", "lemon", "lion"]],
      ["Unit 5", ["milk", "money", "monkey", "mouse", "nest", "net", "nose", "nut", "octopus", "olive", "ostrich", "ox"]],
      ["Unit 6", ["panda", "peach", "pen", "pineapple", "queen", "question", "quilt", "quiz", "rabbit", "rice", "robot", "rose"]],
      ["Unit 7", ["seal", "soap", "socks", "sun", "teacher", "tent", "tiger", "turtle", "umbrella", "umpire", "uncle", "up", "van", "vest", "vet", "violin"]],
      ["Unit 8", ["box", "fox", "six", "watch", "water", "wax", "web", "wolf", "yacht", "yak", "yogurt", "yo-yo", "zebra", "zero", "zipper", "zoo"]],
    ],
  },
  "opw-l2": {
    title: "Oxford Phonics World 2",
    grade: "Level 2",
    units: [
      ["Unit 1", ["ant", "ax", "can", "cat", "dam", "fan", "jam", "man", "pan", "ram", "yak", "yam"]],
      ["Unit 2", ["bag", "bat", "cap", "dad", "hat", "map", "mat", "nap", "pad", "rag", "rat", "tap"]],
      ["Unit 3", ["bed", "egg", "hen", "jet", "net", "pen", "pet", "red", "ten", "vet", "web", "wet"]],
      ["Unit 4", ["bib", "hip", "in", "ink", "kid", "lid", "lip", "rib", "rip", "sip", "tip", "zip"]],
      ["Unit 5", ["big", "bin", "dig", "fig", "fin", "hit", "mix", "pin", "pit", "six", "wig", "win"]],
      ["Unit 6", ["cot", "dot", "fox", "hop", "hot", "log", "mop", "ox", "pop", "pot", "rod", "top"]],
      ["Unit 7", ["bud", "bug", "cup", "hug", "jug", "mud", "mug", "pup", "rug", "sun", "up"]],
      ["Unit 8", ["bun", "cub", "cut", "fun", "gum", "hum", "hut", "nut", "run", "tub"]],
    ],
  },
  "opw-l3": {
    title: "Oxford Phonics World 3",
    grade: "Level 3",
    units: [
      ["Unit 1", ["cake", "cane", "cape", "cave", "game", "gate", "lake", "mane", "name", "skate", "tape", "wave"]],
      ["Unit 2", ["bike", "dive", "fine", "five", "hike", "kite", "lime", "line", "nine", "pine", "ripe", "time"]],
      ["Unit 3", ["bone", "cone", "cube", "cute", "home", "june", "mule", "mute", "rope", "rule", "tube", "tune"]],
      ["Unit 4", ["bay", "day", "hay", "mail", "may", "nail", "pay", "rain", "sail", "say", "tail", "wait"]],
      ["Unit 5", ["bee", "candy", "eat", "feet", "happy", "jeep", "key", "leaf", "meat", "money", "sea", "seed"]],
      ["Unit 6", ["cry", "die", "high", "lie", "light", "my", "night", "pie", "right", "sky", "spy", "tie"]],
      ["Unit 7", ["boat", "bow", "coat", "elbow", "goat", "pillow", "road", "row", "soap", "toad", "window", "yellow"]],
      ["Unit 8", ["blue", "boot", "clue", "dew", "food", "fruit", "glue", "moon", "new", "suit", "tuesday", "zoo"]],
    ],
  },
  "opw-l4": {
    title: "Oxford Phonics World 4",
    grade: "Level 4",
    units: [
      ["Unit 1", ["black", "blanket", "bride", "broom", "clock", "club", "crab", "crocodile", "flag", "fly", "glass", "globe"]],
      ["Unit 2", ["dress", "drum", "friday", "frog", "grass", "green", "plate", "play", "sleep", "slide", "tree", "truck"]],
      ["Unit 3", ["fast", "smile", "smoke", "snake", "snow", "spoon", "spot", "stamp", "stop", "swim", "swing", "test"]],
      ["Unit 4", ["brush", "catch", "chick", "dolphin", "fish", "lunch", "phone", "shell", "ship", "watch", "whale", "white"]],
      ["Unit 5", ["bath", "duck", "father", "mother", "queen", "quilt", "rocket", "teeth", "that", "think", "this", "three"]],
      ["Unit 6", ["adult", "bank", "belt", "camp", "hand", "king", "lamp", "long", "paint", "pink", "tent", "wind"]],
      ["Unit 7", ["desk", "scale", "school", "skunk", "splash", "splint", "spray", "spring", "square", "squid", "string", "strong"]],
      ["Unit 8", ["cage", "cell phone", "cheese", "city", "giant", "giraffe", "ice cream", "jeans", "legs", "orange", "rice", "rose"]],
    ],
  },
  "opw-l5": {
    title: "Oxford Phonics World 5",
    grade: "Level 5",
    units: [
      ["Unit 1", ["bird", "car", "doctor", "farm", "girl", "nurse", "park", "purple", "sister", "star", "teacher", "tractor"]],
      ["Unit 2", ["book", "boy", "brown", "bush", "coin", "cow", "foot", "house", "mouse", "pull", "soil", "toy"]],
      ["Unit 3", ["august", "ball", "board", "draw", "fork", "horse", "prawn", "roar", "sauce", "tall", "walk", "water"]],
      ["Unit 4", ["bear", "bread", "chair", "cheer", "clear", "deer", "ear", "hair", "head", "pear", "share", "square"]],
      ["Unit 5", ["acorn", "baby", "child", "cold", "elevator", "he", "hotel", "lady", "music", "she", "tiger", "uniform"]],
      ["Unit 6", ["banana", "chicken", "gorilla", "honey", "lemon", "love", "monkey", "panda", "pencil", "son", "surprise", "umbrella"]],
      ["Unit 7", ["castle", "comb", "glove", "knee", "knife", "lamb", "live", "rhino", "rhubarb", "whistle", "write", "wrong"]],
      ["Unit 8", ["beautiful", "competition", "dangerous", "excursion", "famous", "helpful", "measure", "nature", "picture", "station", "television", "treasure"]],
    ],
  },
};

/** Minimal kid gloss overrides for phonics content words missing from dict-core */
const GLOSS: Record<string, string> = {
  ant: "蚂蚁",
  apple: "苹果",
  bag: "包",
  banana: "香蕉",
  bed: "床",
  bear: "熊",
  bird: "鸟",
  book: "书",
  boy: "男孩",
  box: "盒子",
  bread: "面包",
  can: "罐头",
  cap: "帽子",
  car: "汽车",
  cat: "猫",
  chair: "椅子",
  computer: "电脑",
  cup: "杯子",
  dad: "爸爸",
  desk: "课桌",
  dog: "狗",
  doll: "玩偶",
  duck: "鸭子",
  ear: "耳朵",
  egg: "鸡蛋",
  fan: "风扇",
  farm: "农场",
  fish: "鱼",
  fork: "叉子",
  fox: "狐狸",
  fun: "有趣",
  gift: "礼物",
  girl: "女孩",
  goat: "山羊",
  hair: "头发",
  hat: "帽子",
  head: "头",
  horse: "马",
  house: "房子",
  ink: "墨水",
  jacket: "外套",
  jam: "果酱",
  jet: "喷气飞机",
  juice: "果汁",
  key: "钥匙",
  king: "国王",
  kite: "风筝",
  lamp: "灯",
  leaf: "叶子",
  lemon: "柠檬",
  lion: "狮子",
  milk: "牛奶",
  money: "钱",
  monkey: "猴子",
  mouse: "老鼠",
  nest: "鸟巢",
  net: "网",
  nose: "鼻子",
  nut: "坚果",
  octopus: "章鱼",
  ox: "公牛",
  panda: "熊猫",
  peach: "桃子",
  pen: "钢笔",
  pencil: "铅笔",
  queen: "女王",
  question: "问题",
  rabbit: "兔子",
  rice: "米饭",
  robot: "机器人",
  rose: "玫瑰",
  seal: "海豹",
  soap: "肥皂",
  sun: "太阳",
  teacher: "老师",
  tent: "帐篷",
  tiger: "老虎",
  turtle: "乌龟",
  umbrella: "雨伞",
  uncle: "叔叔",
  up: "向上",
  van: "厢式货车",
  water: "水",
  watch: "手表",
  zero: "零",
  zoo: "动物园",
  cake: "蛋糕",
  game: "游戏",
  lake: "湖",
  name: "名字",
  bike: "自行车",
  five: "五",
  kite: "风筝",
  line: "线",
  nine: "九",
  time: "时间",
  home: "家",
  day: "天",
  may: "五月",
  rain: "雨",
  say: "说",
  tail: "尾巴",
  happy: "开心的",
  key: "钥匙",
  night: "夜晚",
  coat: "外套",
  goat: "山羊",
  soap: "肥皂",
  yellow: "黄色的",
  blue: "蓝色的",
  food: "食物",
  moon: "月亮",
  zoo: "动物园",
  alligator: "鳄鱼",
  ax: "斧头",
  elbow: "手肘",
  envelope: "信封",
  gorilla: "大猩猩",
  "hot dog": "热狗",
  igloo: "冰屋",
  iguana: "鬣蜥",
  insect: "昆虫",
  kangaroo: "袋鼠",
  ostrich: "鸵鸟",
  olive: "橄榄",
  pineapple: "菠萝",
  quilt: "被子",
  quiz: "小测验",
  seal: "海豹",
  socks: "袜子",
  umpire: "裁判",
  vest: "背心",
  violin: "小提琴",
  wax: "蜡",
  web: "蜘蛛网",
  wolf: "狼",
  yacht: "游艇",
  yak: "牦牛",
  yogurt: "酸奶",
  "yo-yo": "悠悠球",
  zipper: "拉链",
  dam: "水坝",
  ram: "公羊",
  yam: "山药",
  bat: "球棒",
  pad: "垫子",
  rag: "抹布",
  hen: "母鸡",
  bib: "围嘴",
  hip: "髋部",
  lid: "盖子",
  lip: "嘴唇",
  rib: "肋骨",
  rip: "撕开",
  sip: "小口喝",
  tip: "尖端",
  zip: "拉链",
  dig: "挖",
  fig: "无花果",
  fin: "鱼鳍",
  hit: "打",
  mix: "混合",
  pin: "别针",
  pit: "坑",
  wig: "假发",
  win: "赢",
  cot: "小床",
  dot: "点",
  hop: "单脚跳",
  log: "木头",
  mop: "拖把",
  pop: "爆开",
  rod: "杆子",
  bud: "花蕾",
  bug: "虫子",
  hug: "拥抱",
  jug: "罐子",
  mud: "泥",
  mug: "杯子",
  pup: "小狗",
  rug: "小地毯",
  bun: "小圆面包",
  cub: "幼兽",
  cut: "切",
  gum: "口香糖",
  hum: "哼歌",
  hut: "小屋",
  tub: "浴缸",
  cane: "手杖",
  cape: "披风",
  cave: "山洞",
  gate: "大门",
  mane: "鬃毛",
  skate: "滑冰",
  tape: "胶带",
  wave: "波浪",
  dive: "潜水",
  fine: "好的",
  hike: "远足",
  lime: "酸橙",
  pine: "松树",
  ripe: "成熟的",
  bone: "骨头",
  cone: "圆锥",
  cube: "立方体",
  cute: "可爱的",
  june: "六月",
  mule: "骡子",
  mute: "静音的",
  rope: "绳子",
  rule: "规则",
  tube: "管子",
  tune: "曲子",
  bay: "海湾",
  hay: "干草",
  mail: "邮件",
  nail: "钉子",
  pay: "付钱",
  sail: "航行",
  wait: "等待",
  bee: "蜜蜂",
  candy: "糖果",
  eat: "吃",
  feet: "脚",
  jeep: "吉普车",
  meat: "肉",
  sea: "海",
  seed: "种子",
  cry: "哭",
  die: "死",
  high: "高的",
  lie: "躺",
  light: "光",
  my: "我的",
  pie: "馅饼",
  right: "右边",
  sky: "天空",
  spy: "间谍",
  tie: "领带",
  boat: "船",
  bow: "蝴蝶结",
  pillow: "枕头",
  road: "路",
  row: "划船",
  toad: "蟾蜍",
  window: "窗户",
  yellow: "黄色的",
  boot: "靴子",
  clue: "线索",
  dew: "露水",
  fruit: "水果",
  glue: "胶水",
  moon: "月亮",
  new: "新的",
  suit: "套装",
  tuesday: "星期二",
  black: "黑色的",
  blanket: "毯子",
  bride: "新娘",
  broom: "扫帚",
  clock: "时钟",
  club: "俱乐部",
  crab: "螃蟹",
  crocodile: "鳄鱼",
  flag: "旗子",
  fly: "飞",
  glass: "玻璃杯",
  globe: "地球仪",
  dress: "连衣裙",
  drum: "鼓",
  friday: "星期五",
  frog: "青蛙",
  plate: "盘子",
  play: "玩",
  slide: "滑梯",
  truck: "卡车",
  fast: "快的",
  smile: "微笑",
  smoke: "烟",
  snake: "蛇",
  snow: "雪",
  spoon: "勺子",
  spot: "斑点",
  stamp: "邮票",
  stop: "停",
  swim: "游泳",
  swing: "秋千",
  test: "测试",
  brush: "刷子",
  catch: "接住",
  chick: "小鸡",
  dolphin: "海豚",
  lunch: "午餐",
  phone: "电话",
  shell: "贝壳",
  ship: "船",
  whale: "鲸鱼",
  white: "白色的",
  bath: "洗澡",
  father: "爸爸",
  mother: "妈妈",
  rocket: "火箭",
  teeth: "牙齿",
  that: "那个",
  think: "想",
  this: "这个",
  three: "三",
  adult: "大人",
  bank: "银行",
  belt: "腰带",
  camp: "营地",
  hand: "手",
  long: "长的",
  paint: "颜料",
  pink: "粉色的",
  wind: "风",
  scale: "秤",
  school: "学校",
  skunk: "臭鼬",
  splash: "溅水",
  splint: "夹板",
  spray: "喷雾",
  spring: "春天",
  square: "正方形",
  squid: "鱿鱼",
  string: "绳子",
  strong: "强壮的",
  cage: "笼子",
  "cell phone": "手机",
  cheese: "奶酪",
  city: "城市",
  giant: "巨人",
  giraffe: "长颈鹿",
  "ice cream": "冰淇淋",
  jeans: "牛仔裤",
  legs: "腿",
  orange: "橙子",
  doctor: "医生",
  park: "公园",
  purple: "紫色的",
  sister: "姐姐",
  star: "星星",
  tractor: "拖拉机",
  brown: "棕色的",
  bush: "灌木",
  coin: "硬币",
  cow: "奶牛",
  foot: "脚",
  pull: "拉",
  soil: "土壤",
  toy: "玩具",
  august: "八月",
  ball: "球",
  board: "木板",
  draw: "画",
  roar: "吼叫",
  sauce: "酱汁",
  tall: "高的",
  walk: "走路",
  cheer: "欢呼",
  clear: "清楚的",
  deer: "鹿",
  share: "分享",
  acorn: "橡子",
  baby: "宝宝",
  child: "孩子",
  cold: "冷的",
  elevator: "电梯",
  he: "他",
  hotel: "旅馆",
  lady: "女士",
  she: "她",
  uniform: "校服",
  chicken: "鸡",
  honey: "蜂蜜",
  love: "爱",
  son: "儿子",
  surprise: "惊喜",
  castle: "城堡",
  comb: "梳子",
  glove: "手套",
  knee: "膝盖",
  knife: "刀",
  lamb: "小羊",
  live: "居住",
  rhino: "犀牛",
  rhubarb: "大黄",
  whistle: "哨子",
  write: "写",
  wrong: "错误的",
  beautiful: "美丽的",
  competition: "比赛",
  dangerous: "危险的",
  excursion: "短途旅行",
  famous: "著名的",
  helpful: "有帮助的",
  measure: "测量",
  nature: "自然",
  picture: "图片",
  station: "车站",
  television: "电视",
  treasure: "宝藏",
  prawn: "大虾",
  map: "地图",
  mat: "垫子",
  nap: "小睡",
  pan: "平底锅",
  pet: "宠物",
  rat: "老鼠",
  tap: "水龙头",
  vet: "兽医",
  zebra: "斑马",
  bin: "箱子",
  ham: "火腿",
  hog: "猪",
  job: "工作",
  jog: "慢跑",
  kid: "小孩",
  kiss: "亲吻",
  men: "男人们",
  mum: "妈妈",
  peg: "钉子",
  pig: "猪",
  pot: "锅",
  rock: "石头",
  rub: "擦",
  sad: "难过的",
  tin: "锡罐",
  well: "水井",
  wet: "湿的",
  in: "在……里",
  top: "顶部",
  nurse: "护士",
  music: "音乐",
  grass: "草",
  sleep: "睡觉",
};

/** Phonics-sense overrides: prefer over dict-core. */
const POS_FORCE: Record<string, string> = {
  can: "n", // OPW2 short-a CVC: can = 罐头
  may: "n",
  june: "n",
  tuesday: "n",
  friday: "n",
  august: "n",
};

const DISPLAY_FORCE: Record<string, string> = {
  june: "June",
  tuesday: "Tuesday",
  friday: "Friday",
  august: "August",
  may: "May",
};

const EX_FORCE: Record<string, { en: string; zh: string }> = {
  can: { en: "Open the can.", zh: "打开这个罐头。" },
  june: { en: "My birthday is in June.", zh: "我的生日在六月。" },
  tuesday: { en: "We have PE on Tuesday.", zh: "我们星期二有体育课。" },
  friday: { en: "Friday is fun.", zh: "星期五很开心。" },
  august: { en: "August is hot.", zh: "八月很热。" },
  may: { en: "May is a warm month.", zh: "五月很暖和。" },
  bride: { en: "The bride is happy.", zh: "新娘很开心。" },
  adult: { en: "An adult helps the child.", zh: "大人帮助孩子。" },
  giant: { en: "The giant is very tall.", zh: "巨人非常高。" },
  child: { en: "The child is playing.", zh: "孩子在玩。" },
  lady: { en: "The lady is kind.", zh: "这位女士很和善。" },
  son: { en: "He is my son.", zh: "他是我的儿子。" },
  nurse: { en: "The nurse is kind.", zh: "护士很和善。" },
  doctor: { en: "The doctor helps me.", zh: "医生帮助我。" },
  teacher: { en: "My teacher is kind.", zh: "我的老师很和善。" },
  in: { en: "The cat is in the box.", zh: "猫在盒子里。" },
  up: { en: "Put your hand up.", zh: "把手举起来。" },
  he: { en: "He is my friend.", zh: "他是我的朋友。" },
  she: { en: "She is my sister.", zh: "她是我的姐姐。" },
  my: { en: "This is my book.", zh: "这是我的书。" },
  this: { en: "This is a cat.", zh: "这是一只猫。" },
  that: { en: "That is a dog.", zh: "那是一只狗。" },
};

function guessPos(word: string): string {
  const w = lemmaOf(word);
  if (["he", "she", "my", "this", "that"].includes(w)) return "pron";
  if (["in", "up"].includes(w)) return "prep";
  if (
    [
      "dig",
      "hit",
      "mix",
      "win",
      "hop",
      "pop",
      "hug",
      "cut",
      "run",
      "hum",
      "eat",
      "cry",
      "die",
      "lie",
      "pay",
      "say",
      "wait",
      "fly",
      "play",
      "sleep",
      "stop",
      "swim",
      "catch",
      "think",
      "paint",
      "splash",
      "spray",
      "draw",
      "roar",
      "walk",
      "cheer",
      "share",
      "pull",
      "live",
      "write",
      "measure",
      "love",
      "dive",
      "hike",
      "sail",
      "row",
      "rip",
      "sip",
      "zip",
    ].includes(w)
  )
    return "v";
  if (
    [
      "big",
      "red",
      "wet",
      "hot",
      "cute",
      "mute",
      "happy",
      "high",
      "right",
      "new",
      "black",
      "green",
      "fast",
      "white",
      "long",
      "pink",
      "strong",
      "brown",
      "tall",
      "clear",
      "cold",
      "purple",
      "beautiful",
      "dangerous",
      "famous",
      "helpful",
      "wrong",
      "fine",
      "ripe",
      "yellow",
      "blue",
    ].includes(w)
  )
    return "adj";
  if (["three", "five", "six", "nine", "zero"].includes(w)) return "num";
  return "n";
}

async function buildPack(
  id: string,
  meta: { title: string; grade: string; volume: string; curriculum: string },
  units: [string, string[]][],
  byLemma: Map<string, DictCore["words"][number]>,
) {
  const seen = new Set<string>();
  const words: PackWord[] = [];
  const listLines = [`# ${meta.title} · 社区对照表，请对照课本核对`];
  for (const [unit, ws] of units) {
    for (const raw of ws) {
      const word = raw.trim();
      const lemma = lemmaOf(word);
      if (!lemma || seen.has(lemma)) continue;
      seen.add(lemma);
      listLines.push(`${word}\t${unit}`);
      const hit = byLemma.get(lemma);
      // Prefer phonics gloss map so short-a "can" stays 罐头, not dict's 能
      let zh = kidGloss(GLOSS[lemma] ?? GLOSS[word] ?? hit?.zh ?? "", word);
      if (!zh || /^[a-z0-9 '\-]+$/i.test(zh)) zh = GLOSS[lemma] ?? GLOSS[word] ?? "待补中文";
      const pos = POS_FORCE[lemma] ?? guessPos(word) ?? hit?.pos ?? "n";
      const ipa = hit?.ipa || "/–/";
      const examples = EX_FORCE[lemma]
        ? [EX_FORCE[lemma]]
        : [makeExample(DISPLAY_FORCE[lemma] ?? word, pos, zh)];
      words.push({
        word: DISPLAY_FORCE[lemma] ?? hit?.display ?? word,
        lemma,
        ipa,
        pos,
        zh,
        examples,
        unit,
      });
    }
  }
  const pack: WordPack = {
    id,
    title: meta.title,
    curriculum: meta.curriculum,
    grade: meta.grade,
    volume: meta.volume,
    language: "en",
    version: 1,
    words,
  };
  return { pack, listLines };
}

const dict = JSON.parse(await readFile(join(root, "src/data/dict-core.json"), "utf8")) as DictCore;
const byLemma = new Map(dict.words.map((w) => [w.lemma, w]));

const listDir = join(root, "src/data/wordlists");
const packDir = join(root, "src/data/packs");
await mkdir(listDir, { recursive: true });
await mkdir(packDir, { recursive: true });

const summary: string[] = [];

for (const [id, book] of Object.entries(OPW)) {
  const { pack, listLines } = await buildPack(
    id,
    {
      title: book.title,
      grade: book.grade,
      volume: "全册",
      curriculum: "opw",
    },
    book.units,
    byLemma,
  );
  await writeFile(join(listDir, `${id}.txt`), listLines.join("\n") + "\n");
  await writeFile(join(packDir, `${id}.json`), JSON.stringify(pack, null, 2) + "\n");
  summary.push(`${id}\t${pack.words.length} words`);
  console.log(id, pack.words.length);
}

/** Go! Phonics：无公开完整词表，只写空模板，不生成可导入 pack。 */
for (const n of [1, 2, 3, 4, 5]) {
  const stub = [
    `# Go! Phonics Level ${n} · 请从课本填写（官方无公开完整词库）`,
    `# 格式：英文单词\\tUnit N`,
    `# 例：`,
    `# ship\\tUnit 1`,
    `# chat\\tUnit 1`,
    "",
  ].join("\n");
  await writeFile(join(listDir, `go-phonics-l${n}.txt`), stub);
}

await writeFile(
  join(listDir, "PHONICS.md"),
  `# Phonics 词包说明

## Oxford Phonics World（已入库）

- \`opw-l1\` … \`opw-l5\`：按单元整理，可在 App「录入 → 课文词包」导入。
- 来源为社区按册整理（ICSpeak），请对照自家课本核对。

## Go! Phonics / 启思《玩转自然拼读》（缺公开完整表）

官方不提供可下载完整词库。请用 \`go-phonics-l1.txt\` … \`l5.txt\` 按课本填写后：

\`\`\`bash
npx tsx scripts/pack-from-wordlist.ts --list src/data/wordlists/go-phonics-l2.txt \\
  --id go-phonics-l2 --title 'Go! Phonics 2' --grade 'Level 2' --curriculum go-phonics
\`\`\`

再在 \`src/data/packs.ts\` 注册即可。
`,
);

await writeFile(join(listDir, "phonics-index.txt"), summary.join("\n") + "\n");
console.log("done");
